### ISSUE TITLE
你好，我尝试把你写的这个模拟器插件用vue2版本重写一遍，但是发现 fps 值非常低，游戏画面比较卡，想请教一下

### ISSUE THREAD

**Issue by NoFearInMyHeart** [taiyuuki/nes-vue#1]

**Comment by NoFearInMyHeart** [comment]
<template>
  <div :style="`width:${width}px;height:${height}px;background-color:#000;margin:auto;position:relative`">
    <canvas id="game-box" :width="WIDTH" :height="HEIGHT" style="display:inline-block"></canvas>
    <div v-if="stop" @click="gameStart(url)"
         style="position: absolute;top: 50%;left: 50%;transform: translate(-50%, -50%);cursor: pointer;color: #f8f4ed;font-size: 20px;">
      {{ label }}
    </div>
  </div>
</template>

<script>
import jsnes from 'jsnes'

export default {
  props: {
    url: {
      type: String,
      require: true
    },
    autoStart: {
      type: Boolean,
      require: false,
      default: false
    },
    width: {
      type: Number,
      require: false,
      default: 256
    },
    height: {
      type: Number,
      require: false,
      default: 240
    },
    label: {
      type: String,
      require: false,
      default: 'Game Start'
    },
    Controller_P1: {
      type: Object,
      require: false,
      default: () => {
        return {
          UP: 'KeyW',
          DOWN: 'KeyS',
          LEFT: 'KeyA',
          RIGHT: 'KeyD',
          A: 'KeyK',
          B: 'KeyJ',
          SELECT: 'Digit2',
          START: 'Digit1'
        }
      }
    },
    Controller_P2: {
      type: Object,
      require: false,
      default: () => {
        return {
          UP: 'ArrowUp',
          DOWN: 'ArrowDown',
          LEFT: 'ArrowLeft',
          RIGHT: 'ArrowRight',
          A: 'Numpad2',
          B: 'Numpad1'
        }
      }
    }
  },
  watch: {
    url() {
      this.gameReset()
    }
  },
  data() {
    return {
      WIDTH: 256,
      HEIGHT: 240,
      AUDIO_BUFFERING: 512,
      SAMPLE_COUNT: 4 * 1024,
      stop: true,
      audio_ctx: null,
      script_processor: null,
      animationframeID: 0,
      framebuffer_u8: null,
      framebuffer_u32: null,
      SAMPLE_MASK: (4 * 1024) - 1,
      audio_samples_L: null,
      audio_samples_R: null,
      audio_write_cursor: 0,
      audio_read_cursor: 0,
      fpsStamp: null,
      nes: null,
      canvas: null
    }
  },
  mounted() {
    const _this = this

    _this.canvas = document.querySelector('#game-box')

    this.audio_samples_L = new Float32Array(_this.SAMPLE_COUNT)
    this.audio_samples_R = new Float32Array(_this.SAMPLE_COUNT)
    this.nes = new jsnes.NES({
      onFrame: function (framebuffer_24) {
        let i = 0
        for (let y = 0; y < _this.HEIGHT; ++y) {
          for (let x = 0; x < _this.WIDTH; ++x) {
            i = y * 256 + x
            _this.framebuffer_u32[i] = 0xff000000 | framebuffer_24[i] // Full alpha
          }
        }
      },
      onAudioSample: function (l, r) {
        _this.audio_samples_L[_this.audio_write_cursor] = l
        _this.audio_samples_R[_this.audio_write_cursor] = r
        _this.audio_write_cursor = (_this.audio_write_cursor + 1) & _this.SAMPLE_MASK
      },
      sampleRate: _this.getSampleRate()
    })

    if (this.url && this.autoStart) {
      this.gameStart(this.url)
    }
    if (!this.url) {
      throw 'nes-eux missing props: url'
    }
  },
  beforeDestroy() {
    const _this = this

    if (this.fpsStamp) {
      clearInterval(this.fpsStamp)
      this.fpsStamp = null
    }
    
    cancelAnimationFrame(_this.animationframeID)
  },
  methods: {
    getSampleRate() {
      if (!window.AudioContext) {
        return 44100
      }
      let myCtx = new window.AudioContext()
      let sampleRate = myCtx.sampleRate
      myCtx.close()
      return sampleRate
    },
    audio_remain() {
      return (this.audio_write_cursor - this.audio_read_cursor) & this.SAMPLE_MASK
    },
    ignoreSourceError(fun) {
      try {
        fun()
      } catch (e) {
        return
      }
    },
    audio_callback(event) {
      const _this = this

      let dst = event.outputBuffer
      let len = dst.length

      if (_this.audio_remain() < _this.AUDIO_BUFFERING) {
        _this.ignoreSourceError(_this.nes.frame)
      }

      let dst_l = dst.getChannelData(0)
      let dst_r = dst.getChannelData(1)
      for (let i = 0; i < len; i++) {
        let src_idx = (_this.audio_read_cursor + i) & _this.SAMPLE_MASK
        dst_l[i] = _this.audio_samples_L[src_idx]
        dst_r[i] = _this.audio_samples_R[src_idx]
      }

      _this.audio_read_cursor = (_this.audio_read_cursor + len) & _this.SAMPLE_MASK
    },
    keyboard(callback, event) {
      const _this = this
      let player_1 = 1
      let player_2 = 2

      switch (event.code) {
        case _this.Controller_P1.UP: // W
          callback(player_1, jsnes.Controller.BUTTON_UP)
          break
        case _this.Controller_P1.DOWN: // S
          callback(player_1, jsnes.Controller.BUTTON_DOWN)
          break
        case _this.Controller_P1.LEFT: // A
          callback(player_1, jsnes.Controller.BUTTON_LEFT)
          break
        case _this.Controller_P1.RIGHT: // D
          callback(player_1, jsnes.Controller.BUTTON_RIGHT)
          break
        case _this.Controller_P1.B: // 'J' - qwerty, dvorak
          callback(player_1, jsnes.Controller.BUTTON_B)
          break
        case _this.Controller_P1.A: // 'K' - qwerty, azerty
          callback(player_1, jsnes.Controller.BUTTON_A)
          break
        case _this.Controller_P1.SELECT: // Tab
          callback(player_1, jsnes.Controller.BUTTON_SELECT)
          break
        case _this.Controller_P1.START: // Return
          if (_this.audio_ctx.state !== 'running') {
            _this.audio_ctx.resume()
          }
          callback(player_1, jsnes.Controller.BUTTON_START)
          break
        case _this.Controller_P2.UP:
          callback(player_2, jsnes.Controller.BUTTON_UP)
          break
        case _this.Controller_P2.DOWN:
          callback(player_2, jsnes.Controller.BUTTON_DOWN)
          break
        case _this.Controller_P2.LEFT:
          callback(player_2, jsnes.Controller.BUTTON_LEFT)
          break
        case _this.Controller_P2.RIGHT:
          callback(player_2, jsnes.Controller.BUTTON_RIGHT)
          break
        case _this.Controller_P2.B:
          callback(player_2, jsnes.Controller.BUTTON_B)
          break
        case _this.Controller_P2.A:
          callback(player_2, jsnes.Controller.BUTTON_A)
          break
        default:
          break
      }
    },
    fitInParent(canvas) {
      const _this = this

      let parent = canvas.parentNode
      let parentWidth = parent.clientWidth
      let parentHeight = parent.clientHeight
      let parentRatio = parentWidth / parentHeight
      let desiredRatio = _this.WIDTH / _this.HEIGHT
      if (desiredRatio < parentRatio) {
        canvas.style.width = `${Math.round(parentHeight * desiredRatio)}px`
        canvas.style.height = `${parentHeight}px`
      } else {
        canvas.style.width = `${parentWidth}px`
        canvas.style.height = `${Math.round(parentWidth / desiredRatio)}px`
      }
    },
    gameReset() {
      const _this = this

      if (_this.stop) {
        return
      }
      if (_this.script_processor.onaudioprocess) {
        _this.gameStop()
      }
      if (_this.url) {
        _this.gameStart(_this.url)
      }
    },
    gameStop() {
      const _this = this

      if (_this.stop) {
        return
      }
      _this.script_processor.disconnect(_this.audio_ctx.destination);
      _this.script_processor.onaudioprocess = null;
      _this.script_processor = null;
      clearInterval(_this.fpsStamp);
      if ('close' in _this.audio_ctx) {
        _this.audio_ctx.close();
      }
      _this.nes.reset();
      cancelAnimationFrame(_this.animationframeID);
    },
    formatParams(data) {
      let arr = []
      for (let name in data) {
        arr.push(encodeURIComponent(name) + '=' + encodeURIComponent(data[name]))
      }
      arr.push(('v=' + Math.random()).replace('.', ''))
      return arr.join('&')
    },
    gameStart(path) {
      const _this = this
      _this.stop = false
      // const canvas = document.querySelector('#game-box')
      const canvas_ctx = _this.canvas.getContext('2d')
      const image = canvas_ctx.getImageData(0, 0, _this.WIDTH, _this.HEIGHT)

      canvas_ctx.fillStyle = 'black';
      canvas_ctx.fillRect(0, 0, _this.WIDTH, _this.HEIGHT);

      const buffer = new ArrayBuffer(image.data.length);
      _this.framebuffer_u8 = new Uint8ClampedArray(buffer);
      _this.framebuffer_u32 = new Uint32Array(buffer);

      _this.audio_ctx = new AudioContext();

      _this.script_processor = _this.audio_ctx.createScriptProcessor(_this.AUDIO_BUFFERING, 0, 2);
      _this.script_processor.onaudioprocess = _this.audio_callback;
      _this.script_processor.connect(_this.audio_ctx.destination);

      _this._ajax({
        url: path,
        method: 'get',
        success: function (responseText, responseXML) {
          console.log(responseText)
          console.log('________________')
          console.log(responseXML)
          _this.nes.loadROM(responseText)
          _this.fitInParent(_this.canvas)
          _this.fpsStamp = setInterval(() => {
            const fps = _this.nes.getFPS()
            _this.$emit('fpsPerSecond', fps ? fps : 0)
          }, 1000)

          _this.$emit('success')

          _this.animationframeID = requestAnimationFrame(function fn() {
            image.data.set(_this.framebuffer_u8);
            canvas_ctx.putImageData(image, 0, 0);
            _this.animationframeID = requestAnimationFrame(fn);
          })
        },
        error: function (status) {
          console.log(status)
          _this.$emit('error')
          _this.gameStop()
        }
      })

      // const rp = new Promise((resolve, reject) => {
      //   let req = new XMLHttpRequest();
      //   req.open('GET', path);
      //   req.overrideMimeType('text/plain; charset=x-user-defined');
      //   req.onerror = () => {
      //     console.log(`Error loading ${path}: ${req.statusText}`);
      //     reject(`Error loading ${path}: ${req.statusText}`)
      //   };
      //
      //   req.onload = function () {
      //     if (this.status === 200 || this.status === 304) {
      //       try {
      //         console.log('结果')
      //         console.log(this.responseText)
      //         _this.nes.loadROM(this.responseText);
      //         _this.fitInParent(_this.canvas);
      //         _this.fpsStamp = setInterval(() => {
      //           const fps = _this.nes.getFPS();
      //           // emits('fpsPerSecond', fps ? fps : 0);
      //           _this.$emit('fpsPerSecond', fps ? fps : 0)
      //         }, 1000);
      //         resolve(null)
      //       } catch (_) {
      //         console.log(_)
      //         console.error(`Error loading ${path}: rom`);
      //         reject(`Error loading ${path}: rom`)
      //         _this.gameStop();
      //       }
      //     } else {
      //       console.error(`Error loading ${path}: ${req.statusText}`)
      //       reject(`Error loading ${path}: ${req.statusText}`)
      //     }
      //     _this.animationframeID = requestAnimationFrame(function fn() {
      //       image.data.set(_this.framebuffer_u8);
      //       canvas_ctx.putImageData(image, 0, 0);
      //       _this.animationframeID = requestAnimationFrame(fn);
      //     });
      //   };
      //
      //   req.send();
      // })
      //
      // rp.then(() => {
      //   // emits('success')
      //   _this.$emit('success')
      // }, reason => {
      //   // emits('error', reason)
      //   _this.$emit('error', reason)
      // })

      document.addEventListener('keydown', (event) => {
        _this.keyboard(_this.nes.buttonDown, event)
      });
      document.addEventListener('keyup', (event) => {
        _this.keyboard(_this.nes.buttonUp, event)
      });

      // // 游戏画面
      // function onAnimationFrame() {
      //   requestAnimationFrame(onAnimationFrame);
      //   image.data.set(framebuffer_u8);
      //   canvas_ctx.putImageData(image, 0, 0);
      // }
    },
    _ajax(options) {
      options = options || {} // 调用函数时如果options没有指定，就给它赋值{},一个空的Object
      options.method = (options.method || 'GET').toUpperCase() // 请求格式GET、POST，默认为GET
      options.dataType = options.dataType || 'json' // 响应数据格式，默认json
      options.timeout = options.timeout || 30000
      let params = this.formatParams(options.data) // options.data请求的数据
      let xhr
      // 考虑兼容性
      if (window.XMLHttpRequest) {
        xhr = new XMLHttpRequest()
      } else if (window.ActiveObject) {
        // 兼容IE6以下版本
        // xhr = new ActiveXobject('Microsoft.XMLHTTP')
      }

      // 启动并发送一个请求
      if (options.method == 'GET') {
        xhr.open('get', options.url + '?' + params, true)
        xhr.send(null)
        xhr.overrideMimeType('text/plain; charset=x-user-defined')
      } else if (options.method == 'POST') {
        xhr.open('post', options.url, true)
        // 设置表单提交时的内容类型
        // Content-type数据请求的格式
        xhr.setRequestHeader('Content-type', 'application/x-www-form-urlencoded')
        xhr.send(params)
      }

      // 设置有效时间
      // setTimeout(function () {
      //   if (xhr.readySate != 4) {
      //     xhr.abort()
      //   }
      // }, options.timeout)
      /*
        接收
        options.success成功之后的回调函数  options.error失败后的回调函数
        xhr.responseText,xhr.responseXML  获得字符串形式的响应数据或者XML形式的响应数据
      */
      // xhr.onreadystatechange = function () {
      //   if (xhr.readyState == 4) {
      //     let status = xhr.status
      //     if ((status >= 200 && status < 300) || status == 304) {
      //       options.success && options.success(xhr.responseText, xhr.responseXML)
      //     } else {
      //       options.error && options.error(status)
      //     }
      //   }
      // }

      xhr.onload = function () {
        try {
          options.success && options.success(xhr.responseText, xhr.responseXML)
        } catch (_) {
          options.error && options.error(status)
        }
      };
    }
  }
}
</script>

<style scoped>
</style>

**Comment by NoFearInMyHeart** [comment]
<template>
  <div :style="`width:${width}px;height:${height}px;background-color:#000;margin:auto;position:relative`">
    <canvas id="game-box" :width="WIDTH" :height="HEIGHT" style="display:inline-block"></canvas>
    <div v-if="stop" @click="gameStart(url)"
         style="position: absolute;top: 50%;left: 50%;transform: translate(-50%, -50%);cursor: pointer;color: #f8f4ed;font-size: 20px;">
      {{ label }}
    </div>
  </div>
</template>

<script>
import jsnes from 'jsnes'

export default {
  props: {
    url: {
      type: String,
      require: true
    },
    autoStart: {
      type: Boolean,
      require: false,
      default: false
    },
    width: {
      type: Number,
      require: false,
      default: 256
    },
    height: {
      type: Number,
      require: false,
      default: 240
    },
    label: {
      type: String,
      require: false,
      default: 'Game Start'
    },
    Controller_P1: {
      type: Object,
      require: false,
      default: () => {
        return {
          UP: 'KeyW',
          DOWN: 'KeyS',
          LEFT: 'KeyA',
          RIGHT: 'KeyD',
          A: 'KeyK',
          B: 'KeyJ',
          SELECT: 'Digit2',
          START: 'Digit1'
        }
      }
    },
    Controller_P2: {
      type: Object,
      require: false,
      default: () => {
        return {
          UP: 'ArrowUp',
          DOWN: 'ArrowDown',
          LEFT: 'ArrowLeft',
          RIGHT: 'ArrowRight',
          A: 'Numpad2',
          B: 'Numpad1'
        }
      }
    }
  },
  watch: {
    url() {
      this.gameReset()
    }
  },
  data() {
    return {
      WIDTH: 256,
      HEIGHT: 240,
      AUDIO_BUFFERING: 512,
      SAMPLE_COUNT: 4 * 1024,
      stop: true,
      audio_ctx: null,
      script_processor: null,
      animationframeID: 0,
      framebuffer_u8: null,
      framebuffer_u32: null,
      SAMPLE_MASK: (4 * 1024) - 1,
      audio_samples_L: null,
      audio_samples_R: null,
      audio_write_cursor: 0,
      audio_read_cursor: 0,
      fpsStamp: null,
      nes: null,
      canvas: null
    }
  },
  mounted() {
    const _this = this

    _this.canvas = document.querySelector('#game-box')

    this.audio_samples_L = new Float32Array(_this.SAMPLE_COUNT)
    this.audio_samples_R = new Float32Array(_this.SAMPLE_COUNT)
    this.nes = new jsnes.NES({
      onFrame: function (framebuffer_24) {
        let i = 0
        for (let y = 0; y < _this.HEIGHT; ++y) {
          for (let x = 0; x < _this.WIDTH; ++x) {
            i = y * 256 + x
            _this.framebuffer_u32[i] = 0xff000000 | framebuffer_24[i] // Full alpha
          }
        }
      },
      onAudioSample: function (l, r) {
        _this.audio_samples_L[_this.audio_write_cursor] = l
        _this.audio_samples_R[_this.audio_write_cursor] = r
        _this.audio_write_cursor = (_this.audio_write_cursor + 1) & _this.SAMPLE_MASK
      },
      sampleRate: _this.getSampleRate()
    })

    if (this.url && this.autoStart) {
      this.gameStart(this.url)
    }
    if (!this.url) {
      throw 'nes-eux missing props: url'
    }
  },
  beforeDestroy() {
    const _this = this

    if (this.fpsStamp) {
      clearInterval(this.fpsStamp)
      this.fpsStamp = null
    }
    
    cancelAnimationFrame(_this.animationframeID)
  },
  methods: {
    getSampleRate() {
      if (!window.AudioContext) {
        return 44100
      }
      let myCtx = new window.AudioContext()
      let sampleRate = myCtx.sampleRate
      myCtx.close()
      return sampleRate
    },
    audio_remain() {
      return (this.audio_write_cursor - this.audio_read_cursor) & this.SAMPLE_MASK
    },
    ignoreSourceError(fun) {
      try {
        fun()
      } catch (e) {
        return
      }
    },
    audio_callback(event) {
      const _this = this

      let dst = event.outputBuffer
      let len = dst.length

      if (_this.audio_remain() < _this.AUDIO_BUFFERING) {
        _this.ignoreSourceError(_this.nes.frame)
      }

      let dst_l = dst.getChannelData(0)
      let dst_r = dst.getChannelData(1)
      for (let i = 0; i < len; i++) {
        let src_idx = (_this.audio_read_cursor + i) & _this.SAMPLE_MASK
        dst_l[i] = _this.audio_samples_L[src_idx]
        dst_r[i] = _this.audio_samples_R[src_idx]
      }

      _this.audio_read_cursor = (_this.audio_read_cursor + len) & _this.SAMPLE_MASK
    },
    keyboard(callback, event) {
      const _this = this
      let player_1 = 1
      let player_2 = 2

      switch (event.code) {
        case _this.Controller_P1.UP: // W
          callback(player_1, jsnes.Controller.BUTTON_UP)
          break
        case _this.Controller_P1.DOWN: // S
          callback(player_1, jsnes.Controller.BUTTON_DOWN)
          break
        case _this.Controller_P1.LEFT: // A
          callback(player_1, jsnes.Controller.BUTTON_LEFT)
          break
        case _this.Controller_P1.RIGHT: // D
          callback(player_1, jsnes.Controller.BUTTON_RIGHT)
          break
        case _this.Controller_P1.B: // 'J' - qwerty, dvorak
          callback(player_1, jsnes.Controller.BUTTON_B)
          break
        case _this.Controller_P1.A: // 'K' - qwerty, azerty
          callback(player_1, jsnes.Controller.BUTTON_A)
          break
        case _this.Controller_P1.SELECT: // Tab
          callback(player_1, jsnes.Controller.BUTTON_SELECT)
          break
        case _this.Controller_P1.START: // Return
          if (_this.audio_ctx.state !== 'running') {
            _this.audio_ctx.resume()
          }
          callback(player_1, jsnes.Controller.BUTTON_START)
          break
        case _this.Controller_P2.UP:
          callback(player_2, jsnes.Controller.BUTTON_UP)
          break
        case _this.Controller_P2.DOWN:
          callback(player_2, jsnes.Controller.BUTTON_DOWN)
          break
        case _this.Controller_P2.LEFT:
          callback(player_2, jsnes.Controller.BUTTON_LEFT)
          break
        case _this.Controller_P2.RIGHT:
          callback(player_2, jsnes.Controller.BUTTON_RIGHT)
          break
        case _this.Controller_P2.B:
          callback(player_2, jsnes.Controller.BUTTON_B)
          break
        case _this.Controller_P2.A:
          callback(player_2, jsnes.Controller.BUTTON_A)
          break
        default:
          break
      }
    },
    fitInParent(canvas) {
      const _this = this

      let parent = canvas.parentNode
      let parentWidth = parent.clientWidth
      let parentHeight = parent.clientHeight
      let parentRatio = parentWidth / parentHeight
      let desiredRatio = _this.WIDTH / _this.HEIGHT
      if (desiredRatio < parentRatio) {
        canvas.style.width = `${Math.round(parentHeight * desiredRatio)}px`
        canvas.style.height = `${parentHeight}px`
      } else {
        canvas.style.width = `${parentWidth}px`
        canvas.style.height = `${Math.round(parentWidth / desiredRatio)}px`
      }
    },
    gameReset() {
      const _this = this

      if (_this.stop) {
        return
      }
      if (_this.script_processor.onaudioprocess) {
        _this.gameStop()
      }
      if (_this.url) {
        _this.gameStart(_this.url)
      }
    },
    gameStop() {
      const _this = this

      if (_this.stop) {
        return
      }
      _this.script_processor.disconnect(_this.audio_ctx.destination);
      _this.script_processor.onaudioprocess = null;
      _this.script_processor = null;
      clearInterval(_this.fpsStamp);
      if ('close' in _this.audio_ctx) {
        _this.audio_ctx.close();
      }
      _this.nes.reset();
      cancelAnimationFrame(_this.animationframeID);
    },
    formatParams(data) {
      let arr = []
      for (let name in data) {
        arr.push(encodeURIComponent(name) + '=' + encodeURIComponent(data[name]))
      }
      arr.push(('v=' + Math.random()).replace('.', ''))
      return arr.join('&')
    },
    gameStart(path) {
      const _this = this
      _this.stop = false
      // const canvas = document.querySelector('#game-box')
      const canvas_ctx = _this.canvas.getContext('2d')
      const image = canvas_ctx.getImageData(0, 0, _this.WIDTH, _this.HEIGHT)

      canvas_ctx.fillStyle = 'black';
      canvas_ctx.fillRect(0, 0, _this.WIDTH, _this.HEIGHT);

      const buffer = new ArrayBuffer(image.data.length);
      _this.framebuffer_u8 = new Uint8ClampedArray(buffer);
      _this.framebuffer_u32 = new Uint32Array(buffer);

      _this.audio_ctx = new AudioContext();

      _this.script_processor = _this.audio_ctx.createScriptProcessor(_this.AUDIO_BUFFERING, 0, 2);
      _this.script_processor.onaudioprocess = _this.audio_callback;
      _this.script_processor.connect(_this.audio_ctx.destination);

      _this._ajax({
        url: path,
        method: 'get',
        success: function (responseText, responseXML) {
          console.log(responseText)
          console.log('________________')
          console.log(responseXML)
          _this.nes.loadROM(responseText)
          _this.fitInParent(_this.canvas)
          _this.fpsStamp = setInterval(() => {
            const fps = _this.nes.getFPS()
            _this.$emit('fpsPerSecond', fps ? fps : 0)
          }, 1000)

          _this.$emit('success')

          _this.animationframeID = requestAnimationFrame(function fn() {
            image.data.set(_this.framebuffer_u8);
            canvas_ctx.putImageData(image, 0, 0);
            _this.animationframeID = requestAnimationFrame(fn);
          })
        },
        error: function (status) {
          console.log(status)
          _this.$emit('error')
          _this.gameStop()
        }
      })

      // const rp = new Promise((resolve, reject) => {
      //   let req = new XMLHttpRequest();
      //   req.open('GET', path);
      //   req.overrideMimeType('text/plain; charset=x-user-defined');
      //   req.onerror = () => {
      //     console.log(`Error loading ${path}: ${req.statusText}`);
      //     reject(`Error loading ${path}: ${req.statusText}`)
      //   };
      //
      //   req.onload = function () {
      //     if (this.status === 200 || this.status === 304) {
      //       try {
      //         console.log('结果')
      //         console.log(this.responseText)
      //         _this.nes.loadROM(this.responseText);
      //         _this.fitInParent(_this.canvas);
      //         _this.fpsStamp = setInterval(() => {
      //           const fps = _this.nes.getFPS();
      //           // emits('fpsPerSecond', fps ? fps : 0);
      //           _this.$emit('fpsPerSecond', fps ? fps : 0)
      //         }, 1000);
      //         resolve(null)
      //       } catch (_) {
      //         console.log(_)
      //         console.error(`Error loading ${path}: rom`);
      //         reject(`Error loading ${path}: rom`)
      //         _this.gameStop();
      //       }
      //     } else {
      //       console.error(`Error loading ${path}: ${req.statusText}`)
      //       reject(`Error loading ${path}: ${req.statusText}`)
      //     }
      //     _this.animationframeID = requestAnimationFrame(function fn() {
      //       image.data.set(_this.framebuffer_u8);
      //       canvas_ctx.putImageData(image, 0, 0);
      //       _this.animationframeID = requestAnimationFrame(fn);
      //     });
      //   };
      //
      //   req.send();
      // })
      //
      // rp.then(() => {
      //   // emits('success')
      //   _this.$emit('success')
      // }, reason => {
      //   // emits('error', reason)
      //   _this.$emit('error', reason)
      // })

      document.addEventListener('keydown', (event) => {
        _this.keyboard(_this.nes.buttonDown, event)
      });
      document.addEventListener('keyup', (event) => {
        _this.keyboard(_this.nes.buttonUp, event)
      });

      // // 游戏画面
      // function onAnimationFrame() {
      //   requestAnimationFrame(onAnimationFrame);
      //   image.data.set(framebuffer_u8);
      //   canvas_ctx.putImageData(image, 0, 0);
      // }
    },
    _ajax(options) {
      options = options || {} // 调用函数时如果options没有指定，就给它赋值{},一个空的Object
      options.method = (options.method || 'GET').toUpperCase() // 请求格式GET、POST，默认为GET
      options.dataType = options.dataType || 'json' // 响应数据格式，默认json
      options.timeout = options.timeout || 30000
      let params = this.formatParams(options.data) // options.data请求的数据
      let xhr
      // 考虑兼容性
      if (window.XMLHttpRequest) {
        xhr = new XMLHttpRequest()
      } else if (window.ActiveObject) {
        // 兼容IE6以下版本
        // xhr = new ActiveXobject('Microsoft.XMLHTTP')
      }

      // 启动并发送一个请求
      if (options.method == 'GET') {
        xhr.open('get', options.url + '?' + params, true)
        xhr.send(null)
        xhr.overrideMimeType('text/plain; charset=x-user-defined')
      } else if (options.method == 'POST') {
        xhr.open('post', options.url, true)
        // 设置表单提交时的内容类型
        // Content-type数据请求的格式
        xhr.setRequestHeader('Content-type', 'application/x-www-form-urlencoded')
        xhr.send(params)
      }

      // 设置有效时间
      // setTimeout(function () {
      //   if (xhr.readySate != 4) {
      //     xhr.abort()
      //   }
      // }, options.timeout)
      /*
        接收
        options.success成功之后的回调函数  options.error失败后的回调函数
        xhr.responseText,xhr.responseXML  获得字符串形式的响应数据或者XML形式的响应数据
      */
      // xhr.onreadystatechange = function () {
      //   if (xhr.readyState == 4) {
      //     let status = xhr.status
      //     if ((status >= 200 && status < 300) || status == 304) {
      //       options.success && options.success(xhr.responseText, xhr.responseXML)
      //     } else {
      //       options.error && options.error(status)
      //     }
      //   }
      // }

      xhr.onload = function () {
        try {
          options.success && options.success(xhr.responseText, xhr.responseXML)
        } catch (_) {
          options.error && options.error(status)
        }
      };
    }
  }
}
</script>

<style scoped>
</style>

**Comment by NoFearInMyHeart** [comment]
<template>
  <div>
    <div class="box">
      <rom :url="gameUrl" label="Click to Start" @fpsPerSecond="getFps" @success="isSuccessful" @error="getError"
           :width="512" :height="480" ref="eux"/>
      <div class="show-fps">FPS:{{ currentFPS }}</div>
    </div>
    <div>
      <button @click="switchGame">Switch</button>
      <button @click="resetGame">Reset</button>
      <button @click="stopGame">Stop</button>
    </div>
  </div>
</template>

<script>
if (process.BROWSER_BUILD) {
  var bridge = require('~assets/js/bridge').default
  var util = require('~assets/js/util').default
}
import Rom from './components/rom.vue'
export default {
  components: {
    Rom
  },
  data() {
    const _gameList = [
      'http://192.168.31.170:3000/public/Wanpaku Duck Yume Bouken 2.nes',
      'http://192.168.31.170:3000/public/Chip to Dale no Dai Sakusen 2.nes',
      'http://192.168.31.170:3000/public/tank.nes'
    ]
    return {
      gameList: _gameList,
      gameUrl: _gameList[0],
      currentFPS: '0',
      i: 0
    }
  },
  methods: {
    switchGame() {
      this.i++;
      if (this.i === this.gameList.length) {
        this.i = 0
      }
      this.gameUrl = this.gameList[this.i]
    },
    getFps(fps) {
      this.currentFPS = fps.toFixed(2)
    },
    resetGame() {
      if (this.$refs.eux) {
        this.$refs.eux.gameReset()
      }
    },
    stopGame() {
      if (this.$refs.eux) {
        this.$refs.eux.gameStop()
      }
    },
    isSuccessful() {
      console.log('Load successful')
    },
    getError(message) {
      console.log(message)
    }
  }
}
</script>

<style lang="scss" scoped>
@import '~assets/css/base.scss';
.box {
  position: relative;
  display: inline-block;
}

.show-fps {
  position: absolute;
  color: #fffef9;
  text-shadow: 0 0 5px #1e131d;
  top: 5px;
  left: 5px;
}

button {
  margin: 0 10px;
  color: #014a88;
}
</style>

**Comment by taiyuuki** [comment]
不知道你是如何重写的，我这个插件是对jsnes的vue组件化封装，但我对jsnes的底层实现了解不多，所以可能很难帮到你，建议你去看一下jsnes的文档以及它的示例（没记错的话，是用react写的），我当时就是参考它的示例。
